[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools>18.0",
    "setuptools-scm>1.5.4",
    "Cython>=0.22",
    "numpy==1.16.5; python_version=='3.7'",
    "numpy==1.17.3; python_version=='3.8'",
    "numpy; python_version>='3.9'",
]
# uncomment to enable pep517 after versioneer problem is fixed.
# https://github.com/python-versioneer/python-versioneer/issues/193
build-backend = "setuptools.build_meta"