{% set name = "bcolz-zipline" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.post2.tar.gz
  md5: eae95628bb926a78ddcffd9d605c46cd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - setuptools_scm
  run:
    - python
    - numpy

test:
  commands:
    - python -c "import bcolz;bcolz.test()"
  requires:
    - numpy

about:
  home: https://github.com/stefan-jansen/bcolz-zipline
  summary: Columnar and compressed data containers.
  license: BSD-1-Clause
  license_file: LICENSES/BCOLZ.txt
